[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
migration_dir = "supabase/migrations"

[auth]
enabled = true
enable_confirmations = false
enable_signup = true

[auth.external]
google_enabled = true

[storage]
enabled = true
